/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:dropList1:811182:
  println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:dropList1:811182:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:734273:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
    String selectedComPort=dropList1.getSelectedText();
  println("Opening COM Port "+selectedComPort);
  serialPort = new Serial(this, selectedComPort, 9600);
  serialPort.bufferUntil(lf);
  serialPortOpen=true;
  //irPort.write("AT\n");
} //_CODE_:button1:734273:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:256676:
  //println("button2 - GButton >> GEvent." + event + " @ " + millis());
  println("Zero Value");
//  if (calculatedAngleX>180.0f) offsetAngleX=180-calculatedAngleX;
//  if (calculatedAngleX<180.0f) offsetAngleX=
  offsetAngleX=180-trueAngleX;
  offsetBradX=32768-trueBradX;
  
  offsetAngleZ=180-trueAngleZ;
  offsetBradZ=32768-trueBradZ;
  
} //_CODE_:button2:256676:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  dropList1 = new GDropList(this, 20, 10, 120, 80, 3);
  dropList1.setItems(loadStrings("list_811182"), 0);
  dropList1.addEventHandler(this, "dropList1_click1");
  button1 = new GButton(this, 150, 10, 80, 30);
  button1.setText("OpenPort");
  button1.setTextBold();
  button1.addEventHandler(this, "button1_click1");
  label1 = new GLabel(this, 10, 60, 80, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Raw Euler");
  label1.setTextBold();
  label1.setOpaque(true);
  label2 = new GLabel(this, 60, 80, 30, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("X");
  label2.setTextBold();
  label2.setOpaque(true);
  label3 = new GLabel(this, 60, 100, 30, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Y");
  label3.setTextBold();
  label3.setOpaque(true);
  EulerX = new GLabel(this, 90, 80, 80, 20);
  EulerX.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  EulerX.setText("-999");
  EulerX.setTextBold();
  EulerX.setOpaque(true);
  label4 = new GLabel(this, 60, 120, 30, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Z");
  label4.setTextBold();
  label4.setOpaque(true);
  EulerY = new GLabel(this, 90, 100, 80, 20);
  EulerY.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  EulerY.setText("-999");
  EulerY.setTextBold();
  EulerY.setOpaque(true);
  EulerZ = new GLabel(this, 90, 120, 80, 20);
  EulerZ.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  EulerZ.setText("-999");
  EulerZ.setTextBold();
  EulerZ.setOpaque(true);
  label5 = new GLabel(this, 600, 10, 80, 20);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("Calibration");
  label5.setTextBold();
  label5.setOpaque(true);
  label6 = new GLabel(this, 630, 30, 50, 20);
  label6.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label6.setText("Sys");
  label6.setTextBold();
  label6.setOpaque(true);
  label7 = new GLabel(this, 630, 50, 50, 20);
  label7.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label7.setText("Gyro");
  label7.setTextBold();
  label7.setOpaque(true);
  Accel_label1 = new GLabel(this, 630, 70, 50, 20);
  Accel_label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Accel_label1.setText("Accel");
  Accel_label1.setTextBold();
  Accel_label1.setOpaque(true);
  label8 = new GLabel(this, 630, 90, 50, 20);
  label8.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label8.setText("Mag");
  label8.setTextBold();
  label8.setOpaque(true);
  calSysTxt = new GLabel(this, 680, 30, 50, 20);
  calSysTxt.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  calSysTxt.setText("-999");
  calSysTxt.setTextBold();
  calSysTxt.setOpaque(true);
  calGyroTxt = new GLabel(this, 680, 50, 50, 20);
  calGyroTxt.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  calGyroTxt.setText("-999");
  calGyroTxt.setTextBold();
  calGyroTxt.setOpaque(true);
  calAccelTxt = new GLabel(this, 680, 70, 50, 20);
  calAccelTxt.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  calAccelTxt.setText("-999");
  calAccelTxt.setTextBold();
  calAccelTxt.setOpaque(true);
  calMagTxt = new GLabel(this, 680, 90, 50, 20);
  calMagTxt.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  calMagTxt.setText("-999");
  calMagTxt.setTextBold();
  calMagTxt.setOpaque(true);
  label9 = new GLabel(this, 600, 130, 80, 20);
  label9.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label9.setText("AngleX");
  label9.setTextBold();
  label9.setOpaque(true);
  label10 = new GLabel(this, 630, 150, 50, 20);
  label10.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label10.setText("DEG");
  label10.setTextBold();
  label10.setOpaque(true);
  angDegXTxt = new GLabel(this, 680, 150, 80, 20);
  angDegXTxt.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  angDegXTxt.setText("999");
  angDegXTxt.setTextBold();
  angDegXTxt.setOpaque(true);
  label11 = new GLabel(this, 630, 190, 50, 20);
  label11.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label11.setText("BRAD");
  label11.setTextBold();
  label11.setOpaque(true);
  angBRADXTxt = new GLabel(this, 680, 190, 80, 20);
  angBRADXTxt.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  angBRADXTxt.setText("999");
  angBRADXTxt.setTextBold();
  angBRADXTxt.setOpaque(true);
  button2 = new GButton(this, 530, 190, 80, 30);
  button2.setText("Zero");
  button2.addEventHandler(this, "button2_click1");
  Offset = new GLabel(this, 630, 170, 50, 20);
  Offset.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Offset.setText("Offset");
  Offset.setTextBold();
  Offset.setOpaque(true);
  offsetXTxt = new GLabel(this, 680, 170, 80, 20);
  offsetXTxt.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  offsetXTxt.setText("999");
  offsetXTxt.setTextBold();
  offsetXTxt.setOpaque(true);
  label12 = new GLabel(this, 600, 220, 80, 20);
  label12.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label12.setText("AngleZ");
  label12.setTextBold();
  label12.setOpaque(true);
  label13 = new GLabel(this, 630, 240, 50, 20);
  label13.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label13.setText("DEG");
  label13.setTextBold();
  label13.setOpaque(true);
  angDegZTxt = new GLabel(this, 680, 240, 80, 20);
  angDegZTxt.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  angDegZTxt.setText("999");
  angDegZTxt.setTextBold();
  angDegZTxt.setOpaque(true);
  label14 = new GLabel(this, 630, 260, 50, 20);
  label14.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label14.setText("Offset");
  label14.setTextBold();
  label14.setOpaque(true);
  offsetZTxt = new GLabel(this, 680, 260, 80, 20);
  offsetZTxt.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  offsetZTxt.setText("999");
  offsetZTxt.setTextBold();
  offsetZTxt.setOpaque(true);
  label15 = new GLabel(this, 630, 280, 50, 20);
  label15.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label15.setText("BRAD");
  label15.setTextBold();
  label15.setOpaque(true);
  angBRADZTxt = new GLabel(this, 680, 280, 80, 20);
  angBRADZTxt.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  angBRADZTxt.setText("999");
  angBRADZTxt.setTextBold();
  angBRADZTxt.setOpaque(true);
}

// Variable declarations 
// autogenerated do not edit
GDropList dropList1; 
GButton button1; 
GLabel label1; 
GLabel label2; 
GLabel label3; 
GLabel EulerX; 
GLabel label4; 
GLabel EulerY; 
GLabel EulerZ; 
GLabel label5; 
GLabel label6; 
GLabel label7; 
GLabel Accel_label1; 
GLabel label8; 
GLabel calSysTxt; 
GLabel calGyroTxt; 
GLabel calAccelTxt; 
GLabel calMagTxt; 
GLabel label9; 
GLabel label10; 
GLabel angDegXTxt; 
GLabel label11; 
GLabel angBRADXTxt; 
GButton button2; 
GLabel Offset; 
GLabel offsetXTxt; 
GLabel label12; 
GLabel label13; 
GLabel angDegZTxt; 
GLabel label14; 
GLabel offsetZTxt; 
GLabel label15; 
GLabel angBRADZTxt; 